name: Kobo Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"  # tiap 10 menit

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pandas openpyxl gspread oauth2client

      - name: Run script
        run: python kobo_to_excel.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
